# Generated by Django 4.1.5 on 2023-12-13 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadmodel',
            name='fecha_fin',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='actividadmodel',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 2, 43, 57, 660225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='actividadmodel',
            name='num_horas',
            field=models.IntegerField(default=0),
        ),
    ]
