# Generated by Django 4.1.5 on 2023-12-13 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0002_actividadmodel_fecha_fin_actividadmodel_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmodel',
            name='fecha_fin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='actividadmodel',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 2, 46, 5, 416651, tzinfo=datetime.timezone.utc)),
        ),
    ]
