# Generated by Django 4.1.5 on 2023-12-13 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0003_alter_actividadmodel_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmodel',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 2, 46, 19, 881141, tzinfo=datetime.timezone.utc)),
        ),
    ]
