# Generated by Django 4.1.5 on 2023-12-13 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0005_alter_actividadmodel_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmodel',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
